"""first

Revision ID: d9429bd4435a
Revises: 
Create Date: 2023-07-03 22:19:35.425767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9429bd4435a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonim_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('uzvards', sa.String(length=64), nullable=True),
    sa.Column('vards', sa.String(length=64), nullable=True),
    sa.Column('telefons', sa.String(length=64), nullable=True),
    sa.Column('valsts', sa.String(length=64), nullable=True),
    sa.Column('pilseta', sa.String(length=64), nullable=True),
    sa.Column('adrese', sa.String(length=128), nullable=True),
    sa.Column('pasta_index', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anonim_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anonim_user_email'), ['email'], unique=False)

    op.create_table('bilde',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bilde_name', sa.String(length=128), nullable=True),
    sa.Column('bilde_url', sa.String(length=128), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=128), nullable=True),
    sa.Column('prece_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('vards', sa.String(length=64), nullable=True),
    sa.Column('uzvards', sa.String(length=64), nullable=True),
    sa.Column('telefons', sa.String(length=64), nullable=True),
    sa.Column('valsts', sa.String(length=64), nullable=True),
    sa.Column('pilseta', sa.String(length=64), nullable=True),
    sa.Column('adrese', sa.String(length=128), nullable=True),
    sa.Column('pasta_index', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('pasutijums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pasutijuma_datums', sa.DateTime(), nullable=False),
    sa.Column('summa', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('anonim_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['anonim_user_id'], ['anonim_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prece',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artikuls', sa.String(length=16), nullable=True),
    sa.Column('cena', sa.Float(), nullable=False),
    sa.Column('izejmateriali', sa.String(length=300), nullable=True),
    sa.Column('apraksts', sa.String(length=500), nullable=True),
    sa.Column('krasa', sa.String(length=50), nullable=True),
    sa.Column('izmers', sa.String(length=32), nullable=True),
    sa.Column('klase', sa.String(length=50), nullable=True),
    sa.Column('grupa', sa.String(length=50), nullable=True),
    sa.Column('veids', sa.String(length=50), nullable=True),
    sa.Column('titulbildes_id', sa.Integer(), nullable=True),
    sa.Column('titulbildes_url', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['titulbildes_id'], ['bilde.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pasutijums_prece',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artikuls', sa.String(length=16), nullable=True),
    sa.Column('cena', sa.Float(), nullable=True),
    sa.Column('cena_ar_atlaidi', sa.Float(), nullable=True),
    sa.Column('atlaide', sa.Float(), nullable=True),
    sa.Column('veids', sa.String(length=50), nullable=True),
    sa.Column('grupa', sa.String(length=50), nullable=True),
    sa.Column('klase', sa.String(length=50), nullable=True),
    sa.Column('izmers', sa.String(length=32), nullable=True),
    sa.Column('krasa', sa.String(length=50), nullable=True),
    sa.Column('pasutijums_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pasutijums_id'], ['pasutijums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pasutijums_prece')
    op.drop_table('prece')
    op.drop_table('pasutijums')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('bilde')
    with op.batch_alter_table('anonim_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anonim_user_email'))

    op.drop_table('anonim_user')
    # ### end Alembic commands ###
